const express = require('express')
const path = require('path')
const cookieparser = require('cookie-parser')
const application = express()
const handler = require('../Controllers/auth')
const checklogin = require('../middlewares/auth')
application.set('view engine','ejs')
application.set('views',path.resolve('./Views'))
application.use(express.json())
application.use(express.urlencoded({extended: false}))
application.use(cookieparser())
application.get('/login',handler.redirectlogin)
application.get('/register',handler.redirectregister)
application.post('/api/auth/register',handler.handleregistration)
application.get('/api/auth/home',checklogin,handler.redirecthome)
application.post('/api/auth/login',handler.handlogin)
application.get('/api/auth/login',handler.redirecthome)
module.exports = application
